"""empty message

Revision ID: 8905ef06072d
Revises: d4b62885f7ff
Create Date: 2020-02-28 11:39:31.503032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8905ef06072d'
down_revision = 'd4b62885f7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
